[tool.poetry]
name = "angel_system"
version = "0.1.0"
description = ""
authors = ["Kitware, Inc. <kitware@kitware.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
matplotlib = "^3.5.1"
numpy = "^1.22.2"
Pillow = "^8"
simpleaudio = "^1.0.4"
smqtk-detection = {git = "https://github.com/Kitware/SMQTK-Detection", rev = "master"}
torch = "^1.10.2"
torchvision = "^0.11.3"
trimesh = {extras = ["all"], version = "^3.10.2"}
pytorchvideo = "^0.1.5"

[tool.poetry.dev-dependencies]
ipython = "^8.0.1"

[build-system]
requires = ["poetry-core==1.0.7"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."smqtk_plugins"]
# Activity detector
"angel_system.impls.detect_activities.pytorchvideo_slow_fast_r50" = "angel_system.impls.detect_activities.pytorchvideo_slow_fast_r50"
