---
# Output staging directory options.
# These directory paths are interpreted relative to the repository root.
stage_dirs:
  # Example
  #example: some/directory
  {}  # REMOVE WHEN ADDING ENTRIES

basic_downloads:
  # Example
  #- dest: "{{ stage_dirs.example_target }}/filename.txt
  #  url: "https://kitware.com"
  #  sha256: 0000000000000000000000000000000000000000000000000000000000000000
  []  # REMOVE WHEN ADDING LIST CONTENT

# List of files from
girder_file_downloads:
  api_url: "https://data.kitware.com/api/v1"
  by_file_id:
    # Example
    #- file_id: "111111111111111111111111"
    #  sha512: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    #  dest: "{{ stage_dirs.build_itt_base }}/some_file.txt"
    []  # REMOVE WHEN ADDING LIST CONTENT

# List of git repositories to check out at a specific ref and then archive.
# Destination files will be written as GZipped TAR files, so please suffix
# appropriately.
# - checksums should be SHA256
git_repositories:
  # Example
  #- name: unique_repo_name
  #  repo: git@github.com:some_org/some_repo.git
  #  ref: branch_name_or_tag_or_hash
  #  dest: "{{ stage_dirs.example }}/safe_file_name.tar.gz"
  #  checksum: 0000000000000000000000000000000000000000000000000000000000000000
  []  # REMOVE WHEN ADDING LIST CONTENT
