version: "3.4"

services:

  #
  # Build requirements
  #

  workspace-base-dev:
    image: ${PTG_REGISTRY}/workspace-base-dev:${PTG_TAG}
    build:
      context: ..  # repo root
      dockerfile: docker/workspace-base-dev/Dockerfile
      cache_from:
        - ${PTG_REGISTRY}/workspace-base-dev:latest
        - ${PTG_REGISTRY}/workspace-base-dev:${PTG_TAG}
    profiles:
      - build-only


  workspace-build-dev:
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    depends_on:
      - workspace-base-dev
    build:
      context: ..  # repo root
      dockerfile: docker/workspace-build/Dockerfile
      args:
        BASE_IMAGE: workspace-base-dev
        PTG_REGISTRY:  # from .env file
        PTG_TAG:  # from .env file
      cache_from:
        - ${PTG_REGISTRY}/workspace-build-dev:latest
        - ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    profiles:
      - build-only

  #
  # Runnable services
  #

  workspace-shell-dev:
    # Development workspace shell, including source and build mounting.
    # Includes X11 passthrough. Requires XAUTH_FILEPATH to be defined in env.
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    working_dir: "/angel_workspace"
    privileged: true
    network_mode: host
    tty: true
    volumes:
      - /dev/shm:/dev/shm
      # Host sharing
      - ../poetry.lock:/angel_workspace/poetry.lock
      - ../pyproject.toml:/angel_workspace/pyproject.toml
      - ../ros:/angel_workspace/src
      - ./workspace_build.sh:/angel_workspace/workspace_build.sh
      - ./workspace_entrypoint.sh:/angel_workspace/workspace_entrypoint.sh
      - ./workspace_setenv.sh:/angel_workspace/workspace_setenv.sh
      # Build environment things
      - ${WORKSPACE_SHELL_HOST_DIR}/build:/angel_workspace/build
      - ${WORKSPACE_SHELL_HOST_DIR}/install:/angel_workspace/install
      - ${WORKSPACE_SHELL_HOST_DIR}/log:/angel_workspace/log
      - ${WORKSPACE_SHELL_HOST_DIR}/stuff:/angel_workspace/stuff
      # X11 things
      - /tmp/.X11-unix:/tmp/.X11-unix
      # assume this file exists, should be created before running.
      - ${XAUTH_FILEPATH}:/tmp/.docker.xauth
    environment:
      PYTHONDONTWRITEBYTECODE: "true"
      HISTFILE: /angel_workspace/stuff/bash_history
      CYCLONE_DDS_INTERFACE:  # from .env file or parent environment
      SETUP_WORKSPACE_INSTALL:  # from .env file or parent environment
      DISPLAY:  # pull from current environment
      XAUTHORITY: /tmp/.docker.xauth

  workspace-shell-dev-gpu:
    extends:
      service: workspace-shell-dev
    # https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              count: all
              # device_ids: ['0', '3']  # mutually exclusive with count

  workspace-shell-run:
    # Service for running ros2 commands in the context of the image's build
    # workspace.
    image: ${PTG_REGISTRY}/workspace-build-dev:${PTG_TAG}
    working_dir: "/angel_workspace"
    privileged: true
    network_mode: host
    volumes:
      - /dev/shm:/dev/shm
    environment:
      CYCLONE_DDS_INTERFACE:  # from .env file
    command: bash -c ". /angel_workspace/install/setup.bash && bash"
