version: "1.0"
activity_labels: "./config/activity_labels/recipe_coffee.yaml"
steps:
  - id: 0
    activity_id: 1
    description: >-
      Pour 12 ounces of water into liquid measuring cup
    median_duration_seconds: 10
  - id: 1
    activity_id: 2
    description: >-
      Pour the water from the liquid measuring cup into the electric kettle
  - id: 2
    activity_id: 3
    description: >-
      Turn on the kettle
  - id: 3
    activity_id: 4
    description: >-
      Place the dripper on top of the mug
  - id: 4
    activity_id: 5
    description: >-
      Take the coffee filter and fold it in half to create a semi-circle
  - id: 5
    activity_id: 6
    description: >-
      Fold the filter in half again to create a quarter-circle
  - id: 6
    activity_id: 7
    description: >-
      Place the folded filter into the dripper such that the the point of the quarter-circle rests in the center of the dripper
  - id: 7
    activity_id: 8
    description: >-
      Spread the filter open to create a cone inside the dripper
  - id: 8
    activity_id: 9
    description: >-
      Turn on the kitchen scale
  - id: 9
    activity_id: 10
    description: >-
      Place a bowl on the scale
  - id: 10
    activity_id: 11
    description: >-
      Zero the scale
  - id: 11
    activity_id: 12
    description: >-
      Add coffee beans to the bowl until the scale reads 25 grams
  - id: 12
    activity_id: 13
    description: >-
      Pour the measured coffee beans into the coffee grinder
  - id: 13
    activity_id: 14
    description: >-
      Set timer for 20 seconds
    median_duration_seconds: 20
  - id: 14
    activity_id: 15
    description: >-
      Turn on the timer
  - id: 15
    activity_id: 16
    description: >-
      Grind the coffee beans by pressing and holding down on the black part of the lid
  - id: 16
    activity_id: 17
    description: >-
      Pour the grounded coffee beans into the filter cone prepared in step 2
  - id: 17
    activity_id: 18
    description: >-
      Turn on the thermometer
  - id: 18
    activity_id: 19
    description: >-
      Place the end of the thermometer into the water
  - id: 19
    activity_id: 20
    description: >-
      Set timer to 30 seconds # TODO: is this set and start the timer? Other time step has a separate turn on the timer step
    median_duration_seconds: 30
  - id: 20
    activity_id: 21
    description: >-
      Pour a small amount of water over the grounds in order to wet the grounds
  - id: 21
    activity_id: 22
    description: >-
      Slowly pour the water over the grounds in a circular motion. Do not overfill beyond the top of the paper filter
  - id: 22
    activity_id: 23
    description: >-
      Allow the rest of the water in the dripper to drain
    median_duration_seconds: 30 # TODO: how long does this take?
  - id: 23
    activity_id: 24
    description: >-
      Remove the dripper from the cup
  - id: 24
    activity_id: 25
    description: >-
      Remove the coffee grounds and paper filter from the dripper
  - id: 25
    activity_id: 26
    description: >-
      Discard the coffee grounds and paper filter

hmm:
  num_steps_can_jump_fwd: 1
  num_steps_can_jump_bck: 2
  class_mean_conf: 0.1
  class_std_conf: 0.2
